### ISSUE TITLE
Design Tabs

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1071]
goal: design the tabs component.

### Prior art
![screen shot 2017-09-29 at 11 28 53](https://user-images.githubusercontent.com/22662903/31009931-6685753e-a509-11e7-8ea6-db42263892eb.png)

### Pain points
- The current tabs component transform to a Dropdown on mobile
- Tabs are horizontally centered
- Tabs doesn't look like actual tabs

### Tasks
- [ ] Define use case
- [ ] Define mobile behaviour
- [x] Visuals
- [ ] Document on the website

**Comment by joseegm** [comment]
### Use Cases
1. To divide page content under logical grouping.
2. Divide a long form into logical groups of inputs.

### Wireframes
1. Desktop
   ![image](https://user-images.githubusercontent.com/22662903/31076359-00b0e3b0-a77a-11e7-9f2a-335e101ea610.png)
  On tablet sizes and up the tab options are displayed in a row, with the content of every tab underneath.

2. Mobile
  ![image](https://user-images.githubusercontent.com/22662903/31076396-2bdab6b0-a77a-11e7-9970-f24a811ed66c.png)
  On mobile the tabs options are also displayed in one single row but the user can scroll the options horizontally.

**Comment by joseegm** [comment]
@LeoT7508 
I think we are good to go with this one

**Comment by LeoT7508** [comment]
@jinjiahuangsap 

Im adding Jinjia to this issue since he is working on it now.

**Comment by jinjiahuangsap** [comment]
@joseegm @LeoT7508 Hey guys, below are Tabs and how it works on mobile. 

![techne_2 0_tabs](https://user-images.githubusercontent.com/32305332/31192160-0ca9b7ea-a906-11e7-82e7-84213f9c3d3a.jpg)
![starter pages_w tabs_mobile](https://user-images.githubusercontent.com/32305332/31192161-0cac9348-a906-11e7-9fc5-6f91b54d44bc.jpg)

**Comment by joseegm** [comment]
@jinjiahuangsap 
Good first draft of the tabs :)

Still some stuff to be be improved:
1. We only need the left aligned ones, we decided that yesterday on the design meeting.
2. The tabs doesn't look like tabs. That is one of our pain points that we want to solve

For the examples with more content, the tabs should be above the toolbar, not inside the collection content.

**Comment by LeoT7508** [comment]
@joseegm @jinjiahuangsap 

1. We included left aligned tabs and centered tabs to cover both instances if needed. 
2. We experimented with different colored shapes behind the tabs, it didn't work out, this fits in better with the overall design style we have so we will move forward with this design.

**Comment by joseegm** [comment]
@LeoT7508  @jinjiahuangsap 
Guys, we can definitely do better than this. 
The design needs to solve the pain points and one of them is the tabs not looking like tabs.

You can try something like this

![image](https://user-images.githubusercontent.com/22662903/31267081-11fd523e-aa77-11e7-9940-4d5ae98fea1e.png)

It is easily to see the one selected and it "encapsulates" the content bellow visually.

Please note: we are reserving the ALL CAPS only for the actions, all SAP interfaces don't use all caps, but we can get away if we use that wisely.

Let's give this another try, it can be so much better than now.

**Comment by LeoT7508** [comment]
@joseegm 

This isn't about "doing better than this", its about creating a consistent design pattern that fits the existing components and design style we have created to this point. 

This solution for tabs is widely used in design systems everywhere so there is no fundamental issue with a 1px rule below a line of clickable labels with a highlight below the active section. 

Now as it pertains to our design system, this solution works best for reasons listed below:

- Our text button links work exactly the same way, on hover there is a 2px rule that highlights the button. 

- The tabs presented fall right in line with this, it creates less variation for button styles, and creates a repeatable visual experience. 

- This should also be easier to implement for developers, with this solution they don't have to create a whole new button set for tabs, they can just clone our Text Button and add in the tab feature. 

- This solution also scales better than other tab structures, the wider the button shape (like the example you created above) the more space this uses horizontally on the page. The tabs we proposed more effectively use the horizontal space they occupy. This holds especially true on mobile where there isn't much room horizontally and the space needs to be used more efficiently.

Now pertaining to ALL CAPS. We are keeping consistent with our buttons using all caps labels. However I do see some value in creating a version with title case labels since some of the names can get longer. We can create a variation for this and see how it comes out. I would like to stay with ALL CAPS wherever possible. So we will iterate on this and come back with the best solution.
