### ISSUE TITLE
Design Page level Sections

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1117]
Goal: Define the Page level Sections.

### Tasks
1. [x] Define uses cases
2. [x] Design the sections types and layouts
3. [ ] Define Margins
4. [ ] Update design files

**Comment by joseegm** [comment]
### Use cases

The Sections are container elements at the page level that have these main functions:
1. Serve as a container for other components, like forms, table, etc.
2. Keep the vertical flow of the page with consistent spacing
3. Define simple layouts for the components 

### Wireframes

![image](https://user-images.githubusercontent.com/22662903/31495748-1cd6f61a-af59-11e7-85ab-411d23f95c59.png)

All Sections have a standard margin at top and bottom. That will keep the vertical rhythm.

### Types
1. **Simple Section**: This section have the same margin. It will be mainly use to display static information and forms.

    ![image](https://user-images.githubusercontent.com/22662903/31496015-0a5ae8f6-af5a-11e7-8a23-14df20fa9aa8.png)

2. **Section with columns**: This type of sections divide the section content in two columns. Used for forms, etc.

    ![image](https://user-images.githubusercontent.com/22662903/31496134-6cc9032e-af5a-11e7-9cb3-199519ec7b6b.png)

3. **Section with no lateral margins**: This section is used for component that stretch from side to side of the page: like tables, trees, etc.

   ![image](https://user-images.githubusercontent.com/22662903/31496146-784fdc22-af5a-11e7-8a5d-b6c688703950.png)

**Comment by joseegm** [comment]
@LeoT7508 
You guys can include the sections above in the exploration you are doing of the "Details 1" and "Details 2" starter pages.

Main details to be defined are if we are going to have a visual differentiation of the sections, like a separator or something similar, or different background colors.

Also the margins need to be defined as well.

**Comment by LeoT7508** [comment]
@joseegm 

I walked through this with Zack, we should be good to go with this base padding system. 

![stater page - panel spacing guide](https://user-images.githubusercontent.com/28761982/32243219-c739d274-be42-11e7-96a3-c1da5a71c841.png)
