### ISSUE TITLE
Design Page layouts (floor-plans)

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1157]
Goal: Make an inventory, define a list of floor plans with respective wireframes.

### Tasks
- [x] Investigate current page layouts from this source material
    - Current Techne usage: https://sapse.invisionapp.com/d/main#/projects/boards/5484242
    - EC and co. usage: https://sapse.invisionapp.com/d/main#/projects/boards/5496849
    - Service Factory: https://sapse.invisionapp.com/d/main#/projects/boards/5674690
    - Model T: https://sapse.invisionapp.com/d/main#/projects/boards/5695610
    - **Fiori**: https://ux.wdf.sap.corp/fiori-design-web/explore/ Click "Layouts, Floorplans and Frameworks" (no shareable link)
- [ ] Define a list of Page Layouts that can be used to cover as many as posible Use Cases from the investigation.
- [ ] Describe the Use case and the Fundamental Components present on the Page Layouts
- [ ] Create simple wireframes to illustrate the layouts
- [ ] Document

**Comment by gcho1023** [comment]
Wire attached. Up for review and discussion. - one issue is how to define starter pages...are we defining them as floorplans or starter pages? Layouts are the skeleton of the starter pages, if we put them one page, it will be content overload. 
![layouts](https://user-images.githubusercontent.com/32933889/32469534-cdcf66aa-c318-11e7-855e-99e61e650f2e.png)

**Comment by joseegm** [comment]
So, basically these are "Application" level structure layouts. We can call this part that "Application structure" instead of layout -I'm still confused between layouts and floorplans here- so to avoid other people outside the project to be confused let's called "Application Structure".

In short. **Application Structure**: is the main nav + sidebar + content + footer. **Started pages** is what goes inside the content area. @gcho1023 That will answer your question.

Now, Instead giving the the names they have, let's name them by the components they have. So the new names will be:
- Full screen -> Application with no sidebar
- Split screen -> Application with sidebar
- Flexible columns -> Let's skip this from this level since this can be done on the floorplan level as well.

Does that makes sense?

**Comment by gcho1023** [comment]
From competitive analysis even including IBM, Saleforce, Microsoft, and SAP Fiori  along with smaller companies like Mailchimp and so forth - its never called application structure...this is very technical. Layout is very common in design vocabulary and there should have no issues due to mental models..

**Comment by gcho1023** [comment]
Wires updated 
![layouts v 2](https://user-images.githubusercontent.com/32933889/32817883-d6fef786-c985-11e7-97e1-fcc1129a3dcd.png)

**Comment by gcho1023** [comment]
latest wires are all in this link : https://6umx4d.axshare.com/#g=1&p=layouts

**Comment by LeoT7508** [comment]
@joseegm 

Zeplin Link:
https://zpl.io/VKEJEmq

![fundamentalui_website_layouts](https://user-images.githubusercontent.com/28761982/34012711-7054152c-e0da-11e7-8e8c-2e9f43ee22ce.png)
