### ISSUE TITLE
Component Taxonomy match with Fiori

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1330]
### Description
The Fundamental UI Components should have the same name as their Fiori counterpart

### First matching
https://wiki.hybris.com/display/yintfdes/Comparison+of+Fundamental+and+Fiore+Components

### Tasks
 - [x] Fundamental Components comparison against Fiori Components
 - [x] Define the nomenclature and Taxonomy changes
 - [ ] ~Identify missing components in Fundamental UI.~ Posponed

**Comment by joseegm** [comment]
@jeannewalters 
I have reviewed the results of the investigation and there is some improvements that can be made:
1. "All of what is labeled as a Button in Fundamental UI is part of "Action" submenu in Fiore." - This statement is not so clear, we have different types of Buttons, The Dropdown Menu Fundamental have is a different component.
2. The screenshot of the "Lists" under "Cards" is not really Cards that's a normal table where you can select/check the rows. See the example: http://sap.github.io/techne/table.html#table-with-checkbox
3. The Dropdown component is not exactly the same as the ComboBox in fiori. That is still to be decided if a component like that will be part of the Fundamental UI Dropdown or a new component with that functionality.

All others are fine, the similarity is there.

**Comment by joseegm** [comment]
been done on the fundamental repo
