### ISSUE TITLE
Demo Plan B

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#700]
Implement all task of Milestone
https://github.com/SAP/techne/milestone/10

Into the POC at
https://github.com/SAP/techne/tree/cce-2.0
To better utilise the features already in place

### Tasks
- [x] Implement Component Page as per Design on #694 
- [x] Implement Cards Component as per Implementation details at #692 and Design at #678 
- [x] Add list of Components as per #697 and Design from #698 
- [x] Update Global Navigation
