### ISSUE TITLE
Define Color functionality

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#762]
Goal: Define the color system functionaliy, to be used on Techne 2.0. How it works in our case.

### Requirements
1. Can used Across all Components
2. Support theming global

### Tasks
1. [x] Decide which color palette to use, #766 
2. [x] Define individual colors 
3. [x] Document results on wiki page

**Comment by joseegm** [comment]
Results already documented on 
https://github.com/SAP/techne/wiki/Colors
