### ISSUE TITLE
Define which Color System be used on Techne 2.0

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#765]
Goal: Decide the final Color Pallete for Techne 2.0

### Tasks
1. [x] Identify possible solutions #766 
2. [x] Define Functionality of the Color System #762 
3. [x] Document results on wiki page

**Comment by joseegm** [comment]
Documented on
https://github.com/SAP/techne/wiki/Colors

**Comment by xak** [comment]
@joseegm This is out of date. See PR #788

**Comment by joseegm** [comment]
@xak 
Just to understand it correctly

From the info here
https://github.com/SAP/techne/wiki/Colors#palette-details

**We don't have "Groups", we have only Color names and shades, right?**

Can you provide a short for the color names I did it for the group names but, that changed now. Thanks

**Comment by xak** [comment]
Here are the names and shades .. https://github.com/SAP/techne/blob/v2.0/src/styles/core/_settings.scss#L64

**Comment by joseegm** [comment]
@xak
Before I update the documentation again.

**This is the final version of the Pattern? I don't mean the colours values, the Naming Pattern?**

One thing: the name "inverse" doesn't reflect the usage. I'll include those colors inside of "Text" as well. Since they will be light colors, so they don't get confused by "Neutral"

**Comment by xak** [comment]
This is how it is currently implemented ... https://github.com/SAP/techne/blob/v2.0/src/styles/core/_settings.scss#L64

**Comment by joseegm** [comment]
@xak 
That doesn't answer my question. So I'll rephrase it. 

**Is this solution final? It won't change? **

Had already changed a couple times already. So I want to be sure it is stable to document

**Comment by xak** [comment]
I can't say that it won't change but I hope that it does not. It is already documented at http://sap.github.io/techne/www/styles.html.

**Comment by joseegm** [comment]
It is stills needs to be documented on the wiki

@xak 
I still didn't got any answer to 
"One thing: the name "inverse" doesn't reflect the usage. I'll include those colors inside of "Text" as well. Since they will be light colors, so they don't get confused by "Neutral"

Have you consider that?

**Comment by joseegm** [comment]
@xak 
I don't consider this finished till the issue with the "inverse" name is not clarified.

**Comment by joseegm** [comment]
Hi @xak 
Can you please provide an answer to:
"One thing: the name "inverse" doesn't reflect the usage. I'll include those colors inside of "Text" as well. Since they will be light colors, so they don't get confused by "Neutral"

Have you consider that?

**Comment by joseegm** [comment]
Color group name was changed to "text-inverse"

**Comment by joseegm** [comment]
Wiki updated https://github.com/SAP/techne/wiki/Colors
