### ISSUE TITLE
Card Actions UX Elements

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#768]
Goal: Identify, name and describe:  UX Elements for the Card Actions

### Wireframes

![image](https://user-images.githubusercontent.com/22662903/28260520-b97f9b74-6adb-11e7-93ec-50ac1a020533.png)

### Card Actions UX Elements
| Element | Description |
|---|---|
| **Action Button** | Used when the object represented by the Card have only one action<br/><br/> For two or more Actions, the **Action Trigger** with the **Action Menu** Should be used |
| **Actions Trigger** | Located on the top right of the card.<br/><br/> When clicked it shows the **Actions Menu**; the Actions Trigger remains highlighted as long as the **Actions Menu** is displayed. <br/><br/> By clicking the **Action Trigger** when the **Actions Menu** is displayed, it hides the **Actions Menu** and return to normal -not highlighted.   |
| **Actions Menu** | Display the a vertical list of **Actions**. This element can outgrow the dimensions of the card  |
| **Actions Menu Section** | Used to group a set of related **Actions**. Int can include a header as well |
| **Section header** | Give a name for the a **Actions Menu Section**. For example: "Process" for a set of **Actions** like: "Aprove", "Reject", "Cancel".
| **Action** | Perform an action on the object the Card represents.<br/><br/> When hovered by the pointer, it highlights. <br><br/> When clicked it hides the **Actions Menu** and the **Actions Trigger** return to normal  |
| **Action + Icon** | Display an accompanying icon next to the action caption |
| **Separator** | Used to separate tasks that are not related. Only visual guidance |

### Tasks
- [x] Define UX Elements
- [x] Visual design
- [x] Document results in the wiki - https://github.com/SAP/techne/wiki/Card-Actions
- [ ] Update box files

**Comment by LeoT7508** [comment]
@joseegm 

Actions menu. 

![Uploading Screen Shot 2017-07-13 at 11.02.41 AM.png…]()

**Comment by LeoT7508** [comment]
@joseegm 

![screen shot 2017-07-13 at 11 57 20 am](https://user-images.githubusercontent.com/28761982/28178539-7fa070dc-67c4-11e7-8ee0-3a6145886462.png)

**Comment by joseegm** [comment]
@LeoT7508 
Great! Looks great.

From your visuals, there will modifications to the UX Elements
- New Action Sections. That will display the separator lines themselves.
- Sections can have a Section Header.
I'll update that in the comment above.

Some ideas:
1. Having the not hovered link text with the same action color as the hovered background, blue. That will signal that they are clickable. The "..." is also blue.
2. I was thinking about having the Section header integrated in the separator. Like this
  ![image](https://user-images.githubusercontent.com/22662903/28179841-874d5284-6803-11e7-939d-54785aee7698.png)
  Reason for that is: the current one, look hanging in the air misaligned.

    Maybe the Seaction Header text, can be aligned left along with the text of the options, instead of centered

**Comment by LeoT7508** [comment]
@joseegm 

1. I wasn't sure if we should have all the labels the action color blue, it seems like it might be a lot of blue text, but if thats the best UX then we can do that. 

2. Having the Section Header incorporated in the separator creates too much visual noise and disconnects the header from hits section, its cleaner and more connected with only text. The difference in type weight and size is enough to separate it. Also the indent is a pretty standard visual cue that something is a subsection so I think we should be good. I increased the padding above the section header to make it more balanced. 
![screen shot 2017-07-13 at 1 46 37 pm](https://user-images.githubusercontent.com/28761982/28182432-c73143ce-67d1-11e7-9712-a444f6b21a1d.png)

**Comment by jeannewalters** [comment]
I would agree with Leo. This is a drop down with options - they aren't floating links that need to be identified by a specific link "color".

**Comment by joseegm** [comment]
@jeannewalters 
No. Is not a drop down with options. Is not the same function, this is an **Actions Menu**

The dropdown is used to **select one option from many**; in that case the options can be black.

In the case of the **Actions Menu**, the user don't select one option, the user **execute one of the actions**; in that case the Actions should have the action color.

@LeoT7508 
1. I like how the Actions are all with the action color, signaling they can be clicked. That's good now.

2. Agree that it might be more visual noise and disconnection. Now it's indeed more balanced. 

It looks now finished for me.

**Comment by joseegm** [comment]
@LeoT7508 
Please don't forget to update the files on Box.

You can tick the corresponding task on https://github.com/SAP/techne/issues/768#issue-239108212 when that's done

Thanks

**Comment by LeoT7508** [comment]
I wanna make sure buttons are done before I upload new files. Cards have text buttons, once those are done I'll upload new files for everything.

**Comment by joseegm** [comment]
Documented at https://github.com/SAP/techne/wiki/Card-Actions

**Comment by joseegm** [comment]
@LeoT7508 
The spacing and sizes for the **Actions Menu** are different than the normal **Actions** #787.

Can you update this ones as well, I'll put this back to the Visual Column. Thank you

**Comment by LeoT7508** [comment]
@joseegm 

The spacing here doesn't have to be the same as our standard buttons. These are 2 different functions. The padding and spacing here does however follow our 4px design logic, so we should be good here.

**Comment by joseegm** [comment]
@LeoT7508 
All right then this is done
