### ISSUE TITLE
Release Plan B

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#774]
goal: Release Alpha

### Tasks
- [x] Address issues on #754 
- [ ] Add Cards Group inflexions points on #739 
- [ ] Fix website sections as spec at https://github.com/SAP/techne/wiki/Website-Content-Components

### Extra
- [x] Spacing as per https://github.com/SAP/techne/wiki/Spacing-Design-specs
- [ ] Implement Form Inputs https://github.com/SAP/techne/wiki/Form-Inputs
- [ ] Complete Component data and templates
- [x] Implement live Spacing changer
- [ ] Implement live themes changer
