### ISSUE TITLE
Readme is missing basic getting started information

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#779]
goal: improve the main read.me file to point the user how to consume the library

### Task
- [ ] Add information about how to download the library with: **npm** and **bower**
- [ ] Add information on how to consume the library, containing
  - [ ] Full compiled CSS files
  - [ ] Stand alone components
- [ ] Add the information resulting from the tasks above to the "Getting started" page
  http://sap.github.io/techne/www/getting-started.html
  > Note: Temporary solution

**Comment by joseegm** [comment]
### Review results

The readme looks good.

The Getting started page, looks ugly as hell, but we can go with that.

Please note:
1. The tasks are not ticked.
2. This is missing the "review" label. That should be added when this is ready to review.
3. This is missing the PR reference as well.

This can be put to done. Thx.
