### ISSUE TITLE
Actions Visual Design

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#787]
goal: create the visual design for the Actions.
Documented at: https://github.com/SAP/techne/wiki/Actions

### Tasks
- [ ] Visual design for Variants and Wireframes
- [ ] Visual design for the Status
- [ ] Update Wiki
- [ ] Update Box files

### Variants and Wireframes - [Design Specs](https://github.com/SAP/techne/wiki/Actions#wireframes)

![image](https://user-images.githubusercontent.com/22662903/27916218-b957c66a-6268-11e7-8b4d-af0ffa69f80c.png)

### Spacing - [Action Spacing Design Specs](https://github.com/SAP/techne/wiki/Actions#spacing) - [Spacing Design Specs](https://github.com/SAP/techne/wiki/Spacing-Design-specs)

![image](https://user-images.githubusercontent.com/22662903/28012218-681c4f96-6565-11e7-901f-c7c8b10bbbd0.png)

### Status - [Status Design Spec](https://github.com/SAP/techne/wiki/Actions#status)

| Status | Description |
|---|---|
| Normal | The default state of the action. Using an [Primary Action](https://github.com/SAP/techne/wiki/Colors#palette-details) color |
| Hover | Light change of color/background color when cursor is hovering. Use a shade of the [Primary Action](https://github.com/SAP/techne/wiki/Colors#palette-details) color  |
| Focused | Signal to the user the current button have the focus. Use a visual effect like glow or a visible border. |
| Active | Only when pressed. It should signal the action is been pressed. Use a shade of [Primary Action](https://github.com/SAP/techne/wiki/Colors#palette-details) color |
| Disabled | The action should be visually less prominent. It cannot be clicked or focused. |

**Comment by joseegm** [comment]
@LeoT7508 
You can start on this. Thanks.

**Comment by LeoT7508** [comment]
@joseegm 

Focused feels like the same as Hover. Doesn't seem like we need it for Buttons.

**Comment by joseegm** [comment]
@LeoT7508 

Focused is for users that don't use a mouse/pointer device. They navigate the forms and elements on the page with the Tab key, that's why we have to signal when the button get the focus, then they can trigger the button with the Space key.

Any other info you may need?
The spacing is clear?

**Comment by LeoT7508** [comment]
@joseegm 

I started on the button design. This is the just start of the variations. I have more, but its not completely thought out yet. 

I'm not sure what spacing you are using above but thats not what I will be using in the system I'm creating. The spacing and padding will continue to evolve as we design new components. For now the padding and spacing I thought through is included in the files attached. I will continue working on this tomorrow and will most likely have the majority available to share. 

Thanks. 

![techne_2 0_square button guidelines](https://user-images.githubusercontent.com/28761982/28088971-03b18ca4-664d-11e7-99a1-5de008b65549.jpg)
![techne_2 0_text button guidelines](https://user-images.githubusercontent.com/28761982/28088972-03c02232-664d-11e7-9b7e-548eb6a94d81.jpg)

**Comment by joseegm** [comment]
@LeoT7508 
Okay. Good start.

**One important thing**: We have a spacing system for the whole library now. It means all the components have to play along with that system. 

You can see the details over here: https://github.com/SAP/techne/wiki/Spacing-Design-specs
And also how they works for the cards over here
https://techne-alpha.firebaseapp.com/components/structure/spacing

That means all spacing, can be defined in pixels first, using 10 and its multiples. For that, 5, 10, 15, 20, 25, etc. That will give us the ability to scale up and down the size of the components very easily.

This is very important. The same way we need a system for the colors, we need this spacing system to work all over the components.

Please let me know if you need further clarification on that and we can have a chat about it. This is a killer feature of the library and it needs to be take in count.

**Comment by LeoT7508** [comment]
@joseegm 

I decided to post the spacing test here since I didn't see a new issue created for it and I didn't want to wait another day for you to see the proposal @xak and I worked on. 

Zack proposed we use a system divisible by 4 since it will match our type system and it fits with the icon system we already have. 

It also seems to work better than the 5 system you have now. See the examples below. The icons work better with the fields and the button text and size feel more comfortable. Overall the 4 system seems to scale a lot better and fits the design system we are currently working with.  

Let me know if u have any questions. 

Thanks. 

![screen shot 2017-07-12 at 3 21 10 pm](https://user-images.githubusercontent.com/28761982/28138337-19a6698e-6716-11e7-9994-8443aae848e3.png)

**Comment by joseegm** [comment]
@LeoT7508 
Thanks for not waiting. Next time you can open the issue as well if you want, we just need a descriptive title for those.

That looks good. Changing the base is not a big deal, if it looks good after all.

This will mean the base for the system is not 10, but 8.

Thanking that in count you don't have to put the the exact pixels anymore on the visuals, just, use the notation: a, 2a, 3a, etc. When a = 8.

I'll update that in the documentation.

**Comment by joseegm** [comment]
So based on that you can check if these spacing and dimensions are still fine.
 
![image](https://user-images.githubusercontent.com/22662903/28155710-1c8fc574-67b0-11e7-8806-f0d920106563.png)

**Comment by LeoT7508** [comment]
@joseegm 

Everything you said makes sense except the base unit. It should be 4. All the units we use are divisible but 4. So a would be 4, 2a is 8, 3a is 12, and so on.

**Comment by joseegm** [comment]
That will be a way to do it. 

I find it more easy to have the more common spacing -probably 8px- as *a* instead of *2a*.
But the end result is the same.

@LeoT7508 
In that case the spacing mentioned above have to be refined to match *a=4*, it is done for *a=10* not *a=5*.
But the proportions you have are a little bit different anyway.

**Comment by LeoT7508** [comment]
@joseegm 

I updated the specs for buttons. 

![techne_2 0_square button guidelines](https://user-images.githubusercontent.com/28761982/28224244-01385c5c-6894-11e7-9ead-b3c405db3e8e.jpg)
![techne_2 0_text buttons](https://user-images.githubusercontent.com/28761982/28224245-013baef2-6894-11e7-8aae-04e83f5d93c3.jpg)


I did some work on how icons and buttons work together. But I will have a more concrete answer when we work on the Action Bar.

**Comment by joseegm** [comment]
@LeoT7508 

On the flat buttons:

1. The hover status: you can try to use a light background color. The difference in color is not noticeable as with the Standard button background.

2. The Active status doesn't have any big differentiator.

3. You can try and use the same frame for focused as the Standard instead of only the shadow. 

Thanks

**Comment by LeoT7508** [comment]
@joseegm 

After some thought, we are going to stick with this for the text buttons. I added a 2px line under the text on hover and focused states to show more emphasis on the action. Since we still have a secondary button that might be needed we can create another style for that. 

![techne_2 0_text buttons](https://user-images.githubusercontent.com/28761982/28427723-c1cd88f0-6d3c-11e7-9905-f1085b7b7e56.jpg)

**Comment by joseegm** [comment]
@LeoT7508 Thanks.
Okay, that's more emphasis.

We can continue with the other variants now, here for context:
![image](https://user-images.githubusercontent.com/22662903/28454814-eb42b136-6dfc-11e7-9158-c96872831ffa.png)

**Can you please post the images in .PNG format?** 
That way they won't loose quality, right now is jpg, so it loose details with the compression. Thanks.

**Comment by LeoT7508** [comment]
@joseegm 
![techne_2 0_square button guidelines](https://user-images.githubusercontent.com/28761982/28479510-5567ade4-6e22-11e7-998f-1bd4d244ae66.png)
![techne_2 0_text buttons](https://user-images.githubusercontent.com/28761982/28479509-5566ae8a-6e22-11e7-8d5e-1a0f6497d1c9.png)

**Comment by joseegm** [comment]
Thanks @LeoT7508 

There are some things missing:
1. The **Flat + Icon** and **Standard + Icon**
2. The status of the buttons **when an icon is present** for both: **Flat** and **Standard**
3. The sizes for the icons, we only have the spacing of the elements now.

**Comment by xak** [comment]
As noted in #840, icon button implementation will remain incomplete until the icons are implemented.

**Comment by LeoT7508** [comment]
@joseegm 

Updated Action Buttons. 

![techne_2 0_square button guidelines](https://user-images.githubusercontent.com/28761982/28639951-b3b809f2-720f-11e7-8127-88933af63df0.png)
![techne_2 0_text button w icon](https://user-images.githubusercontent.com/28761982/28639953-b4888410-720f-11e7-87d3-1790e10fae1b.png)
![techne_2 0_text buttons](https://user-images.githubusercontent.com/28761982/28639952-b3c832fa-720f-11e7-9b1b-1d4c0e0a3df7.png)

**Comment by joseegm** [comment]
Updating documentation based on the final visuals, not types defined on the wireframes

**Comment by joseegm** [comment]
Updated documentation at https://github.com/SAP/techne/wiki/Actions

**Comment by joseegm** [comment]
@xak 
This is ready for development.
