### ISSUE TITLE
Design Check boxes

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#801]
goal: check boxes style.

### Current
<img width="197" alt="screen shot 2017-07-13 at 11 48 54" src="https://user-images.githubusercontent.com/22662903/28160708-5525305c-67c1-11e7-988b-140bd22b84dc.png">

### Pain points
1. Disproportional label text in relation with the Check box element size
2. Low contrast of the label

### Tasks
- [x] Define use cases
- [x] Visual design
- [x] Document results on wiki: https://github.com/SAP/techne/wiki/Check-Boxes
- [x] Update files on Box

**Comment by joseegm** [comment]
### Use Cases

The main use case for a **Check Box** is to mark a setting, option or flag as active. 

For instance: 

- [ ] Send promotional emails to my email address

- [ ] Use this *object* as reference

### UX Elements
![image](https://user-images.githubusercontent.com/22662903/28368890-3a898e94-6c96-11e7-8ae1-99507095411f.png)

| Element | Description |
|---|---|
| Input | The element that can reflect the status of the checkbox. Checked or Unchecked |
| Label | The label describes what will happen when the checkbox is activated  |

### Status
![image](https://user-images.githubusercontent.com/22662903/28369268-5ff1f1b6-6c97-11e7-9d9e-c34368c41175.png)

| Status | Description |
|---|---|
| Normal | The **Check Box** doesn't have the focus.  |
| Mandatory | Setting a **Check Box** as mandatory means: the user have to activate the option to validate the screen or continue with the flow. The label is displayed in bold and a `*` at the end, indicating that field is mandatory. <br/><br/> This is the only case where the **Check Box** can be put to **Invalid** after performing the validation. |
| Focused | Like the rest of the **Form Inputs** the Input Element will highlight indicating to the user that the element have the focus. Only the input element will be highlighted, not the Label  |
| Disabled | The Input element and the label are dimmed/grayed out so signal they cannot be used |
| Invalid | The **Input Element** with highlight in a *error* color and a message will be displayed right bellow the **mandatory checkbox** |

**Comment by joseegm** [comment]
@LeoT7508 
These are the uses cases and status for the **Check Box**. 
Please take in count the pain points from https://github.com/SAP/techne/issues/801#issue-242646618

**Comment by LeoT7508** [comment]
@joseegm 

![techne_2 0_checkboxes](https://user-images.githubusercontent.com/28761982/28479536-6db72d20-6e22-11e7-8612-11b0c83a0200.png)

**Comment by joseegm** [comment]
Looking good, thanks @LeoT7508.

### Things to improve

1. The checked check box is blue. When putting the check boxes along with other inputs. That color will draw too much attention to it. see attached screenshot:

    ![screen shot 2017-07-25 at 11 32 40](https://user-images.githubusercontent.com/22662903/28565696-386cc68a-712d-11e7-9ce0-0f692c94240c.png)

2. The checked check box with the square filled looks very heavy in comparison with the other inputs -see above screenshot. **We can try removing the fill and using only the check icon inside the square.

3. There is no apparent difference between the focused and the checked.

### Let's try this

Put the Normal checked checkbox color to black, leaving only the blue for the focused status. That will solve 1, 2 and 3

**Comment by joseegm** [comment]
@LeoT7508
There is also a unbalance with the error messages. We are going to try and find a better solution that works for the inputs as well as the check boxes. The ticket is opened at #841

**Comment by LeoT7508** [comment]
@joseegm 

These comments are addressed the same way as radio buttons.

**Comment by LeoT7508** [comment]
@joseegm 

Updated Check Boxes

**Comment by joseegm** [comment]
Results documented on:
https://github.com/SAP/techne/wiki/Check-Boxes

**Comment by joseegm** [comment]
@xak 
This is ready for implementation.
