### ISSUE TITLE
Design Radio buttons

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#802]
goal: design the radio buttons and solve the current pain points

### Current
<img width="544" alt="screen shot 2017-07-13 at 11 49 00" src="https://user-images.githubusercontent.com/22662903/28160920-e670adb6-67c1-11e7-968a-cf4cbb57324c.png">

### Pain points
1. Disproportional label text in relation with the Check box element size
2. Low contrast of the label

### Tasks
- [x] Define use cases
- [x] Visual design
- [x] Document results on wiki: https://github.com/SAP/techne/wiki/Radio-Buttons
- [x] Update files on Box

**Comment by joseegm** [comment]
### Use Cases

The radio buttons main use is to **select a single option** from a set of options that are visible and comparable all the time.

### UX Elements
![image](https://user-images.githubusercontent.com/22662903/28371088-42bfe12a-6c9c-11e7-9ad8-7a0570afcedd.png)

| Element | Description |
|---|---|
| Label | This label is used to group all radio buttons in the set  |
| Input | The element that can be selected |
| Option Label | The **Option Label** describes the particular option so the user can make the selection |

### Status
![image](https://user-images.githubusercontent.com/22662903/28371713-0149f422-6c9e-11e7-88d1-c871e3f9dfc0.png)

| Status | Description |
|---|---|
| Normal | The **Radio buttons** doesn't have the focus.  |
| Mandatory | Setting a **Radio Button group** as mandatory means: the user have to select one option to validate the screen or continue with the flow. <br/><br/> The **Label** is displayed in bold and a `*` at the end, indicating that field is mandatory. The **Option Labels** are not displayed in bold or have the `*`. <br/><br/> This is the only case where the **Radio Button** can be put to **Invalid** after performing the validation. |
| Focused | Like the rest of the **Form Inputs** the **Input Element** will highlight indicating to the user that the element have the focus. Only the input element will be highlighted, not the Option Labels  |
| Disabled | The Input element and the Option Labels are dimmed/grayed out to signal they cannot be used |
| Invalid | The **Input Element** will highlight in a *error* color and a message will be displayed right bellow the **set of options** |

**Comment by joseegm** [comment]
@LeoT7508 
This are the elements for the radio buttons. They are similar to the **Check boxes**.

**Comment by LeoT7508** [comment]
@joseegm 

![techne_2 0_radio buttons](https://user-images.githubusercontent.com/28761982/28479609-c145eeae-6e22-11e7-91c3-7981faecfaf1.png)

**Comment by joseegm** [comment]
This looks very good @LeoT7508, thanks.

### Some points to improve:

1. The normal selected status is blue. When putting the radio buttons along with other inputs. That color will draw too much attention to it. see attached screenshot:
    
    ![screen shot 2017-07-25 at 11 19 07](https://user-images.githubusercontent.com/22662903/28565117-8bcd0972-712b-11e7-9ee8-b82e86b5eace.png)



2. Also it is the color we use for the **Focused** input. So, it will looks like the radio button is always focused.

 3. There is no apparent difference between between the focused and the selected.

### Let's try this
    
Put the **Normal selected** radio button color to black, leaving only the blue for the focused status. That will solve 1, 2 and 3

**Comment by joseegm** [comment]
@LeoT7508 
There is also a unbalance with the error messages. We are going to try and find a better solution that works for the inputs as well as the radio buttons. The ticket is opened at #841

**Comment by LeoT7508** [comment]
@joseegm 

The colors used for the radio buttons are all the same that I used for inputs. To keep it consistent we will stick with what we have. 

The obvious difference between focused and selected is, selected has the filled inner circle while focused has only the outlined circle. Thats very clear.

To keep things consistent we will stay with this for now. If we get feedback of too much color or emphasis then we can make a change.

**Comment by LeoT7508** [comment]
@joseegm 

Updated Radio Buttons. 

![techne_2 0_radio buttons](https://user-images.githubusercontent.com/28761982/28640093-33c7eb26-7210-11e7-9737-bd8744efeb2e.png)

**Comment by joseegm** [comment]
@LeoT7508 

One small thing: In the case of the radio buttons, the error message doesn't belong to only one option radio button. The user select one option from all.

So in this case:
<img width="560" alt="screen shot 2017-07-27 at 13 43 12" src="https://user-images.githubusercontent.com/22662903/28668738-9daf3ed8-72d1-11e7-9a55-04f246735150.png">

The error message should be aligned left with the label, not with the last option.

Once that is corrected, we are good to go with this one.

**Comment by LeoT7508** [comment]
@joseegm 

Updated. 

![techne_2 0_radio buttons](https://user-images.githubusercontent.com/28761982/28677910-86fb89d4-72b4-11e7-9c47-a8f87f394987.png)

**Comment by joseegm** [comment]
Results documented on
https://github.com/SAP/techne/wiki/Radio-Buttons

**Comment by joseegm** [comment]
@xak 
This is ready for development.
