### ISSUE TITLE
Design Table

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#807]
goal: design the table component

### Current v1.5.x 
<img width="666" alt="screen shot 2017-07-13 at 12 26 01" src="https://user-images.githubusercontent.com/22662903/28162189-87a8b3be-67c6-11e7-830b-9fd1b4c43189.png">

### Tasks
- [ ] Define Use Cases
- [ ] Define UX Elements
- [x] Define row status
- [x] Visual Design
- [ ] Document results

**Comment by LeoT7508** [comment]
@xak 

![techne_2 0_table60pxrows](https://user-images.githubusercontent.com/28761982/29787608-2a86fe04-8bf5-11e7-8671-3526d1ab419f.png)
