### ISSUE TITLE
Design Tool bar

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#810]
goal: design and improve the toolbar

### Current v1.5.x
<img width="970" alt="screen shot 2017-07-13 at 12 38 37" src="https://user-images.githubusercontent.com/22662903/28162679-3a9416de-67c8-11e7-94ab-01f6e7ba065d.png">

### Tasks
- [x] 1. Define use cases
  - [x] 1. Define **Filtering** 
  - [ ] 2. Define **Search** 
  - [x] 3. Define **Pagination** 
  - [x] 4. Define **Views**
  - [x] 5. Define **Actions** - new 
- [x] Define UX Elements for 1
- [x] Visual Design
- [x] Document results

**Comment by LeoT7508** [comment]
@xak 

![techne_2 0_titlebar](https://user-images.githubusercontent.com/28761982/29940844-21105628-8e56-11e7-8fe0-41d73c0c9dbe.png)
