### ISSUE TITLE
Design Status indicators

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#814]
goal: define and design more flexible status indicators

### Current v1.5.x
<img width="466" alt="screen shot 2017-07-13 at 12 58 14" src="https://user-images.githubusercontent.com/22662903/28163411-47be473c-67cb-11e7-8963-2f30ae8b1e59.png">

### Tasks
- [ ] Define Uses cases
  - [ ] Define specific uses for every type of indicators
- [ ] Define UX Elements
- [x] Visual Design

**Comment by xak** [comment]
@LeoT7508 You could take a look at these. 

# Note 
In Bootstrap 4 these are called "Badges" — https://getbootstrap.com/docs/4.0/components/badge/
Previously they were "Labels" which is how we refer to them — https://techne.yaas.io/components/Status-Indicators.html

**Comment by LeoT7508** [comment]
@xak 

![techne_2 0_status indicators](https://user-images.githubusercontent.com/28761982/29682917-4d60456e-88d2-11e7-87a8-bd0dce2d486e.png)
