### ISSUE TITLE
Action Bar Visual Design

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#824]
goal: Style the UX Elements of the Action Bar - defined on #793 

### Reference Use Cases wireframes
![image](https://user-images.githubusercontent.com/22662903/28270116-9e26318e-6b04-11e7-90c3-110fb2545252.png)

![image](https://user-images.githubusercontent.com/22662903/28270123-a2e1dffc-6b04-11e7-82e3-0f82a8c49427.png)

![image](https://user-images.githubusercontent.com/22662903/28270130-a93f2562-6b04-11e7-863a-875ad44498ab.png)

![image](https://user-images.githubusercontent.com/22662903/28270137-b0e207da-6b04-11e7-8dcf-1f98004f2f07.png)

![image](https://user-images.githubusercontent.com/22662903/28270144-b97a701c-6b04-11e7-90b0-af045f6b4d16.png)

![image](https://user-images.githubusercontent.com/22662903/28270148-be6fd4a4-6b04-11e7-913c-12cd419dbdc8.png)

![image](https://user-images.githubusercontent.com/22662903/28270155-c2ef7296-6b04-11e7-8bb1-2472bd840df6.png)

![image](https://user-images.githubusercontent.com/22662903/28270165-cd68d992-6b04-11e7-8717-0b8e3b48d5cb.png)

Detailed description of the Uses Cases at https://github.com/SAP/techne/wiki/Action-Bar-Design#uses-cases-and-ux-elements-behaviour

### Tasks
- [ ] Visuals for Location element
- [ ] Visuals for Back button
- [ ] Visuals for Actions element
  - [ ] Visuals for Actions States: enabled, disabled
- [ ] Document on the wiki
- [ ] Update files on Box

**Comment by joseegm** [comment]
Visual design happening at #759. So closing this one
