### ISSUE TITLE
Revisit website Component Page

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#842]
goal: Find the important uses cases and re-structure the Component website elements to address those.

### Current status

There is a discordance on the wireframes and the visual design.

| Wireframes | Visuals |
|---|---|
| ![image](https://user-images.githubusercontent.com/22662903/28473213-ee594b22-6e43-11e7-994f-43d34b4a3a94.png) | ![28473278-31fe2578-6e44-11e7-93a7-e96cb5b45017](https://user-images.githubusercontent.com/22662903/28473370-87616ef8-6e44-11e7-9de6-e4065160fc8f.png) | 

### Tasks
- [ ] 1. Define use cases
- [ ] 2. Define user flows
- [ ] 3. Define the Structure of the Component Page
- [ ] 4. Define the Interaction
- [ ] 5. Create wireframes reflecting point: 1 to 4
- [ ] 6. Visual Design 
- [ ] 7. Document on wiki https://github.com/SAP/techne/wiki/Website-Component-page-Design
- [ ] 8. Update files on box

**Comment by joseegm** [comment]
Include CSS structure from #786

**Comment by jeannewalters** [comment]
Here are the wires for the Component page - one right rail, one without.
Here are the links to axshare:
http://6umx4d.axshare.com/#g=1&p=component_template_no_right_rail
http://6umx4d.axshare.com/#g=1&p=component_template_right_rail

@LeoT7508 , please ask Amy any follow up questions so that we can keep moving along. I will be out until next Wed.
![component_template_no_right_rail](https://user-images.githubusercontent.com/24274321/32347041-6911dbc8-bfdd-11e7-8a79-6fa45ac71070.png)
![component_template_right_rail](https://user-images.githubusercontent.com/24274321/32347042-6920ae64-bfdd-11e7-9251-3ef20cd67697.png)

**Comment by LeoT7508** [comment]
@jinjiahuangsap

**Comment by LeoT7508** [comment]
@joseegm @jeannewalters 

These are on Zeplin. They are ready from a design side.

**Comment by joseegm** [comment]
I'm opening this again since we are making some changes as discussed.
