### ISSUE TITLE
Techne new Name transition

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#850]
goal: Find and transition the project to a new name.

### Tasks - WIP
- [x] Brainstorm and find name candidates, via internal survey
- [x] Vote on the new names collected to select the final candidates
- [x] Summit the final names candidates to the SAP naming team

- [ ] Open a new repo under github.com/SAP/fundamental (fundamental, ng-fundamental) - Jose

CSS namespace: fd

### After Beta

- [ ] Change name space
  - [ ] Change name space on the library
  - [ ] Change name space on the site and rest of documentation
- [ ] Migrate website to the new name
  - [ ] Migrate continuous 
- [ ] NPM and co.
- [ ] CDN, also on ondeman.com --investigate - Jose 
- [ ] Testing and Staging environments -- investigate - Jose
- [ ] Whitesource integration
- [ ] Integrate with Dev portal and other properties that pull information from the repo

> More tasks will be added as they are appearing.

**Comment by joseegm** [comment]
outdated and already done at the same time
