### ISSUE TITLE
Docs: Design Styles website page

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#851]
goal: design the layout and how the sections of the page will looks like.

### Personas goals on this page:
- Decision maker: 
    1. Check if there is a coherent foundation for all styles and components
    2. Check if there is a corresponding with the main brand
    3. Check themes possibilities
    4. Learn about the support for accesibility
- Designer:
    1. Learn the style foundations
    2. Use colors and fonts
    3. Download/Access design resources
    4. Learn about the themes possibilities
- Developer:
    1. Get color codes for use on development
    2. Get Font information

### Final page structure #726
1. Main usage copy text: Emphasising the Business UX
2. Techne philosophy
3. Use of Color
4. Themes - To be defined
5. Info and link to Team Q - Style and Standard Guidelines
6. Accessibility info - To be defined

### Tasks
- [x] Wireframes for the page structure sections
- [ ] Design interaction of the section elements
- [ ] Visual design
- [ ] Document in wiki
- [ ] Update Box files

**Comment by joseegm** [comment]
### First wireframe draft
![image](https://user-images.githubusercontent.com/22662903/28720130-9030118e-73ac-11e7-950a-139886853bac.png)

**Comment by joseegm** [comment]
Themes and more in deep Accessibility info will be treated separately as soon as we have more info on that.

**Comment by saadmhybris** [comment]
@LeoT7508 - is there a design for this page? or should be just based off the wireframe. 

@like-me1 - you can start on the task once leo confirms.

**Comment by LeoT7508** [comment]
@saadmhybris 

As of now the UX for this page was still up for debate so no there is no final design.

**Comment by jeannewalters** [comment]
Here are the templates - 
Landing Template: http://6umx4d.axshare.com/#g=1&p=content_template
General Content Template: http://6umx4d.axshare.com/#g=1&p=landing_template

Landing Template :
![landing_template](https://user-images.githubusercontent.com/24274321/32347245-0294ec9a-bfde-11e7-9dfa-a94d54a2f25b.png)

Content Template:
![content_template](https://user-images.githubusercontent.com/24274321/32347272-192db1bc-bfde-11e7-876f-bd6035457284.png)

**Comment by LeoT7508** [comment]
@jeannewalters @joseegm 

This is fine, however we need real content, I can lay this out but its not going to look like anything. @joseegm I need content from you to work on this page. Ill assign it to you.

**Comment by gcho1023** [comment]
the wireframe above is outdated...the page has been split by the new sitemap we created

**Comment by LeoT7508** [comment]
@gcho1023 @joseegm 

Then we need to update the ticket, or we need to create separate tickets. These tickets are starting to get confusing.

**Comment by gcho1023** [comment]
we dont need to create any new tickets...they are already in the visual column

**Comment by joseegm** [comment]
@LeoT7508 This issues is outdated, thanks to @gcho1023  for creating individual tickets for every page.
