### ISSUE TITLE
Add the Warning status to the Form inputs

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#852]
goal: add Warning as Form input status 

### Tasks
- [x] Define use case for Warning
- [ ] Update visuals
- [ ] Update documentation in wiki: https://github.com/SAP/techne/wiki/Form-Inputs
- [ ] Update files on Box

**Comment by joseegm** [comment]
### Warning use case
The warning messages will be displayed when the data entered on the input is not valid -like a date in the past- but that is not preventing from continuing with the flow.

### Visual representation
The "error message" will be displayed in warning color, like orange. With a accompanying icon.


![image](https://user-images.githubusercontent.com/22662903/28771087-cb417dbc-75e1-11e7-9673-7050a8a7130d.png)

**Comment by joseegm** [comment]
@LeoT7508 
Please update the visuals https://github.com/SAP/techne/wiki/Form-Inputs#form-inputs-status-763

Notice that the icon should be different from one in use for the errors.

**Comment by LeoT7508** [comment]
@joseegm 

Is the request here to make a variation of the instance attached but with an orange color?

![screen shot 2017-08-01 at 12 01 46 pm](https://user-images.githubusercontent.com/28761982/28837126-464bf224-76b1-11e7-8f5b-4eb567781b1f.png)

**Comment by joseegm** [comment]
@LeoT7508 
Yes, with a different icon as well, so color blind users can differentiate.
Please note that the error icon should be more "urgent" than the warning one; at this point we can change both.

**Comment by LeoT7508** [comment]
@joseegm 

![techne_2 0_inputfields](https://user-images.githubusercontent.com/28761982/28879264-54b859ea-7767-11e7-86a0-c3d29ac87030.png)

**Comment by LeoT7508** [comment]
@joseegm @saadmhybris 

This issue can be closed. All design tasks have been approved by design.
