### ISSUE TITLE
Add new color group for Backgrounds

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#853]
Goal: add new color group for backgrounds.

### Problem
Wrong color group is been used for background purposes
https://github.com/SAP/techne/pull/844#pullrequestreview-52599014

### Solution
Add a new color group `background` to put background colors.
1. Add the first shade as white  `#FFFFFF`

### Tasks
- [x] Update Visual representation of color groups
   https://github.com/SAP/techne/wiki/Colors#visual-representation
- [ ] Update Documentation on wiki https://github.com/SAP/techne/wiki/Colors#palette-details
- [ ] Update files on box

**Comment by LeoT7508** [comment]
@joseegm 

![techne_2 0_colorpalette_master](https://user-images.githubusercontent.com/28761982/28792001-e0f0ed84-75f3-11e7-94a8-2dd4e110e7b3.png)

**Comment by joseegm** [comment]
@LeoT7508 
Neutral Shade 5 and 6 have the same Hexadecimal code.

We need a better solution to manage colors than a photoshop file or the wiki.
To solve problems like this one.

**Issue opened on #854**
