### ISSUE TITLE
Docs: Migrate Techne Website delivery to Jekyll

### ISSUE THREAD

**Issue by saadmhybris** [SAP/techne#855]
Goal: Use Jekyll to power techne documentation site.

**Current Status:** 
- [V2.0 branch](https://github.com/SAP/techne/tree/v2.0) has the most up to date Techne 2.0 component code
- There is already separation between the library and the documentation site 

**Tasks for completing the migration to Jekyll:** 
- [x] Replace ./docs folder with Jekyll
- [x] Integrate Jekyll server with Gulp to serve local dev site 
- [x] Setup Barebone structure for the site. 
- [x] migrate content from the previous version of the site (old v2.0 content that was already done) 
- [x] Compile SCSS code with gulp for both the library and documentation site. 
- [x] Live reload for local development 
- [x] Code snippet component should be driven by the component code to reduce redundancy. 
- [x] Port 1.5 components that don't require redesign - added as a separate task this is a relatively big undertaking. discussions to continue here -  #858
- [x] Deployment for dev, staging, prod - moving this out to its own task as this should not be a blocker for this ticket to be completed and merged #857
 
Development branch for this task is not under feature/855-jekyll

**Comment by saadmhybris** [comment]
FYI Jekyll will not regenerate when .yml files are touched. 

Issue discussed here - https://github.com/jekyll/jekyll/issues/3854

**Comment by saadmhybris** [comment]
Changed the goal of the task to just the migration to Jekyll to serve up the documentation site. 

1.5 component migration and MVP discussion to be handled in separate tickets.
