### ISSUE TITLE
Update color pallete

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#856]
goal: update the visual representation of the palette at https://github.com/SAP/techne/wiki/Colors#visual-representation

### Tasks

- [ ] Change  Color group name from "Inverse" to "Text-Inverse"
- [ ] Split the "Status" group into 3 new color groups: 
    1. Valid
    2. Warning
    3. Error
- [ ] Add the corresponding new shades to Warning and Error
    ![screen shot 2017-08-03 at 10 24 49](https://user-images.githubusercontent.com/22662903/28912801-02945c0c-7836-11e7-8969-3f34ad440773.png)

- [ ] Check that all Hex values correspond with the colors correctly
- [ ] Update Wiki page https://github.com/SAP/techne/wiki/Colors
- [ ] Update file on box

**Comment by LeoT7508** [comment]
@joseegm @saadmhybris 

![techne_2 0_colorpalette_master](https://user-images.githubusercontent.com/28761982/28928855-02d75d60-7834-11e7-89ae-faa40f9a3377.png)

This is updated on Box and Invision.

**Comment by xak** [comment]
Hey guys, I don't think separating the statuses makes sense. If this was being implemented as software (and it is), these would be grouped under a class like "Status" since they are closely related and have all the same properties, they would not be implemented as standalone classes.

As I mentioned in a previous issue, we can use color adjustment techniques when there is a direct relationship between the two colors used on the same element. Hovers fit that, a status background or border fit that. This will help us keep the palette lean which is better for theming.

It will be up to design to specify these adjustments, a simple note that the hover is 10% lighter will suffice.

**Comment by LeoT7508** [comment]
@xak 

Thanks, sounds like this makes sense for a development side. I will make the adjustments based off their recommendation. 

I'll update all files with to match what was discussed. 

This issue is closed.

**Comment by joseegm** [comment]
I will move this to done, but we may need to go back to this again because the proposed technical solution doesn't scale.

Discussion about the technical solution is at: 
https://github.com/SAP/techne/pull/844
