### ISSUE TITLE
Design Main UI Layout

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#998]
goal: Define and wireframe the components of the a whole screen UI.

## Tasks
- [x] Define and wireframe the elements
- [x] Define the responsive behavior
- [ ] Document on the wiki

**Comment by joseegm** [comment]
### Main App UI elements

![image](https://user-images.githubusercontent.com/22662903/30429840-44a5da0a-9959-11e7-8633-5298bbcc4fa0.png)

| Element | Description |
|---|---|
| Global Bar | Displays the product/app name and logo as well as user profile avatar and other important information. Not used for main navigation.
| Side Bar | Display the main navigation options for the product/app. |
| Content | This area display the main UI elements. |

**Comment by joseegm** [comment]
## Responsive behaviour

![image](https://user-images.githubusercontent.com/22662903/30430047-2e8f95e8-995a-11e7-9f30-bee4992973d3.png)

On a mobile device, the Side Bar is hidden, the Global Bar displays a "Menu" icon that will display the Side Bar when tapped.

![image](https://user-images.githubusercontent.com/22662903/30430266-fc38f82c-995a-11e7-911f-383e91001dba.png)

Once the "Menu" is tapped the Side Bar slides over the whole content of the screen.

**Comment by joseegm** [comment]
@xak 
These are the main elements for building an whole screen with our library. The exact details and dimensions of the Global bar and the Side Bar will be done on their respective issues.

If we are good with this we can continue to flesh the Global and Side Bar and define a couple layouts for inside the Content area.

**Comment by xak** [comment]
@joseegm This doesn't show what the UI should look like at each breakpoint nor does it show how the global menu should behave responsively. I do not recommend combining the global and side nav into one view — it's difficult to maintain. The current behavior stacks the global and sidenavs allowing them to be their own thing — https://devportal.yaas.io/tools/

Consider optimizing the global UI to the screen size. On medium size screens, we can auto minimize the sidebar to a narrow band that appears on hover/tap to provide more real estate for the content. At small screen the side bar goes to the top. At large sizes, the sidebar is always open when real estate is not a problem.

![screen shot 2017-09-14 at 10 18 36 am](https://user-images.githubusercontent.com/424119/30438527-0de27c16-9937-11e7-9e4b-bb8c354dd8bf.png)

**Comment by joseegm** [comment]
I will like to avoid the current situation that we have right now, with 2 top bars.
![screen shot 2017-09-15 at 16 13 24](https://user-images.githubusercontent.com/22662903/30486499-0900e610-9a31-11e7-95d5-5be701c23ca8.png)

The Side Navigation will not contain the navigation elements of the Global Bar. Those elements will collapse on their own when responding to a small screen. The Side bar will not become a second bar as it is right now.

This tasks is to define the behaviour of the main elements, not the content inside, those will be defined on their respective tasks.

The idea of having a small version of the Side bar can be done, we'll see when we get to it.

**Comment by xak** [comment]
My concern with this approach is that it creates a dependency for the global nav to "know about" the side nav, i.e, show the hamburger or not? Even if the hamburger is shoved up we'd still have to reposition the logo based on whether the sidebar is present or not. The application must be aware of `hasSideNavigation` only for presentational purposes.

The minimized narrow band sidebar still leaves plenty of room for content on tablets (portrait). This approach is nice because only the smallest phone screens need the stacked bars of navigation, which admittedly is not ideal, but not uncommon.

Given that small screen views are not used greatly, the path of least resistance seems the best option. Is it worth forcing every application using Techne to maintain template-level presentation logic for the sake of avoiding a narrow band at the top of the app on a phone?

**Comment by joseegm** [comment]
I don't think we need to force the implementation that the two bars work together.

Let's do this:
1. Make the Global Bar to support the hamburger menu
2. Make the Side Bar to support hiding and showing
3. Suggest the proposed behaviour on the documentation and let the teams to implement it.

That way we avoid having a global state like "hasSideNavigation"

I think with that we'll be in a good place for all cases.

The partially contracted Side bar we can also have.

**Comment by LeoT7508** [comment]
@jeannewalters @gcho1023 

Can you guys look this over? I think its still up for grabs.

**Comment by jeannewalters** [comment]
After we decide on the approach for navigation, we will revisit this.

**Comment by joseegm** [comment]
with the new context this is not much relevant anymore, the layout components are already on the library as scaffold for the other navigation components
